FORMAT: 1A9
HOST: http://reference.iqmetrix.net/

# Reference

## TimeZones [/TimeZones]

### Get All TimeZones [GET]

+ Response 200 (application/json)

        [
            {
                "Id": "Alaskan Standard Time",
                "Name": "(UTC-09:00) Alaska",
                "SupportsDaylightSavingTime": true
            }
        ]    