#%RAML 0.8
title: reference
baseUri: https://reference.iqmetrix.net/v2
resourceTypes:
    - collectionReadOnly:
        get:
            headers:
              Accept:
                example: application/json    
            responses:
                200:
                    body:
                        application/json:
                          schema: <<resource>>
schemas:
  - TimeZone: |
      {
        "name": "TimeZone",
        "type": "array",
        "$schema": "http://json-schema.org/draft-03/schema",
        "properties": {
          "Id": { "type": "string", "description": "Identifier", "example": "Alaskan Standard Time" }, 
          "Name": { "type": "string", "description": "Name", "example": "(UTC-09:00) Alaska" },
          "SupportsDaylightSavingTime": { "type": "boolean", "description": "A flag to indicate if this TimeZone observes Daylight Savings Time", "example": "true" }
        }
      }
/TimeZones:
  type:
    collectionReadOnly:
      resource: TimeZone
  get: 
    displayName: Get All Time Zones